[alias]
test-local = "test --target=x86_64-unknown-linux-gnu"

# Output in tests not working as of now - no tests found
#[target.x86_64-unknown-linux-gnu]
#runner = "bash defmt-print-runner.sh"
#rustflags = [
#  "-C", "target-feature=+crt-static",
#  "-C", "relocation-model=static",
#  "-C", "link-arg=-T/usr/lib/x86_64-linux-gnu/ldscripts/elf_x86_64.x",
#  "-C", "link-arg=-Tdefmt.x",
#]

[target.thumbv6m-none-eabi]
runner = 'probe-run --chip stm32l053r8t6'

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
